name: TTD Scraper

on:
  workflow_dispatch: # Only runs when manually triggered (via button or API call)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: |
          echo "$GOOGLE_SHEETS_JSON" > service_account.json
          python ttd_sheet_scraper.py
