name: TTD Scraper Daily Run

on:
  schedule:
    - cron: '0 0 * * *' # This runs every day at midnight. Change as needed.
  workflow_dispatch:      # This allows you to click a button and run it manually.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Scraper
        env:
          GOOGLE_SHEETS_JSON: ${{ secrets.GOOGLE_SHEETS_JSON }}
        run: |
          echo "$GOOGLE_SHEETS_JSON" > service_account.json
          python ttd_sheet_scraper.py
